// Generated by CoffeeScript 1.8.0
(function() {
  module.exports = function(grunt) {
    grunt.initConfig({
      pkg: grunt.file.readJSON('package.json'),
      sass: {
        dist: {
          files: [
            {
              expand: true,
              cwd: "static/scss",
              src: ['**/*.scss'],
              dest: 'static/css',
              ext: '.css'
            }
          ]
        }
      },
      watch: {
        css: {
          files: ['**/*.scss'],
          tasks: ["sass"],
          option: {
            spawn: false
          }
        }
      }
    });
    grunt.loadNpmTasks('grunt-contrib-watch');
    grunt.loadNpmTasks('grunt-contrib-sass');
    grunt.registerTask("default", function() {
      return grunt.task.run(["sass", "watch"]);
    });
    return grunt.registerTask("build", ['sass', "watch"]);
  };
}).call(this);
